//
// DO NOT MODIFY THIS FILE.
//
// This file is automatically generated using the behavior_tree_translator.py script
// on the file: ../../Assets/Behavior Tree Definitions\bt_always_pass.xml
//

using BattleTech;


public static class AlwaysPass_BT
{
    public static BehaviorNode InitRootNode(BehaviorTree behaviorTree, AbstractActor unit, GameInstance game)
    {
        BraceNode always_pass_root = new BraceNode("always_pass_root", behaviorTree, unit);

        return always_pass_root;
    }
}
